### ISSUE TITLE
Compatible option for ajax views

### ISSUE THREAD

**Issue by davidsosavaldes** [davidsosavaldes/Attire#10]
Mentioned on #9

**Comment by yespbs** [comment]
The update was already merged, we just need to create a new layout for ajax and use that without extending master layout.

example

1. application/theme/{your_theme}/layouts/ajax.twig
    `{% block content %}

	{% for view,params in views %}
		{% include view with params %}
	{% endfor %}
	
      {% endblock %}`

2. in your controller use this with render return ( second parameter )
   `$this->attire
      ->set_theme('your_theme)
      ->set_layout('ajax')
      ->add_view('path/to/your/ajaxed_view', $view_data)
      ->render([], true);`


gist: https://gist.github.com/yespbs/8d5f9ea1bfd49ca93d078f2974980c2e
