### ISSUE TITLE
Message: Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#11]
Hola (molestando de nuevo jeje)
Estoy obteniendo el siguiente mensaje de error cuando quiero correr un template:

> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\punk\application\libraries\attire\Attire.php:754)
> 
> Filename: core/Common.php
> 
> Line Number: 569
> 
> Backtrace:
> 
> File: C:\xampp\htdocs\punk\application\libraries\attire\Attire.php
> Line: 767
> Function: show_error
> 
> File: C:\xampp\htdocs\punk\application\controllers\admin\login.php
> Line: 50
> Function: render
> 
> File: C:\xampp\htdocs\punk\index.php
> Line: 294
> Function: require_once
> 
> Attire::render()
> 
> Unable to add function "ci_*" as extensions have already been initialized.

Esto sucede cuando quiero devolver una vista despues de hacer un post de un formulario.

Mi controlador esta armado asi:
```php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Login extends Admin_Controller {

	public function __construct(){
		parent::__construct();
	}	

	public function index()
	{
		//echo include_stylesheet('admin/global/css/*');exit();
		/*if ( $this->aauth->is_loggedin() ){
			echo 'OK. You are logged in';
		} else {
			
			$data['css'] = "page-md login";
			
			$this->attire->set_layout('login/login',$data);
			$this->attire->render();
		}*/  
	}
	public function login()
	{
		if($this->input->post('remember'))
		{
			if($this->aauth->login($this->input->post('username'), $this->input->post('password'), true))
			{
				redirect('admin/index', 'refresh');
			}
			else
			{
				$data['errors'] = '';//$this->aauth->print_errors();
				$this->attire->set_layout('login/login',$data);
				$this->attire->render();
			}
		}
		else
		{
			if($this->aauth->login($this->input->post('username'), $this->input->post('password')))
			{
				redirect('admin/index', 'refresh');
			}
			else
			{
				//echo"Error 2<pre>";print_r($this->aauth->print_errors());echo"</pre>";exit();
				$data['errors'] = '';//$this->aauth->print_errors();
				$this->attire->set_layout('login/login',$data);
				$this->attire->render();

			}
		}
		
	}

}

/* End of file login.php */
/* Location: ./application/controllers/login.php */
```
la clase Admin_Controller es la siguiente:
```php
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class My_Controller extends CI_Controller {

	public $debug;
	public $ci;

	public function __construct(){
		parent::__construct();
		$this->ci =& get_instance();
		
		$this->load->library('user_agent');
		$this->load->library('attire/attire');
		
		//$this->load->library('Datatables');
        //$this->load->library('table');

		$this->ci->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));
		
	}

}

class Admin_Controller extends MY_Controller {
	public $debug;
	public $ci;

	public function __construct(){
		parent::__construct();
		$this->ci =& get_instance();

		$data['project'] = "Punk Framework";
		$data['title'] = "Administración - ";

		//$this->load->library("Aauth");
		$this->attire->set_theme('admin');

		if (!$this->aauth->is_loggedin() ){
			$data['css'] = "page-md login";
			$data['title'] .= 'Login';
			
			$this->attire->set_layout('login/login',$data);
			$this->attire->render();
		}

	}

}

/* End of file my_Controller.php */
/* Location: ./application/controllers/my_Controller.php */
```

estoy haciendo algo mal?

saludos

**Comment by davidsosavaldes** [comment]
Saludos Lucas, no será porque tienes la libreria aauth comentada?

        //$this->load->library("Aauth");

Como comentario adicional, dentro de los controladores de Codeigniter no es necesario cargar una instancia:

    $this->ci =& get_instance(); #no debería de cargarse

Para utilizar a `form_validation` tienes que cargar la librería:

    $this->load->library('form_validation');

Después llamalo de la siguiente manera:

    $this->form_validation

En ves de:

    $this->ci->form_validation

**Comment by oniricosistemas** [comment]
Hola, 
al parecer el problema existe cuando mi controlador se extiende de una clase nieta, es decir:
Padre_Controller -> Hjijo_Controller -> Controller
en mi caso

```PHP
class My_Controller extends CI_Controller {
...

class Admin_Controller extends MY_Controller {
....

class Login extends Admin_Controller {
```

porque cuando mi controlador hereda de My_Controller funciona correctamente. Será por como esta armanda mi clase Admin_Controller.
La librerias las cargue directamente desde el autoload asi no las cargo desde los controladores.

Saludos

**Comment by davidsosavaldes** [comment]
Es una excelente observación, tendremos en cuenta revisar el comportamiento de la librería de la forma en que comentas.
