### ISSUE TITLE
add_view no funciona

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#13]
Hola estimado,
en esta ocasión molesto porque estoy intentando agregar una vista junto al rederizados del template y no me estaría funcionando. En el controller tengo esto:
```php
class Admin extends MY_Controller {

	public function __construct()
	{
		parent::__construct();
		$this->attire->set_theme('admin');
	}

	public function index()
	{
		$data = array();
		if ( $this->aauth->is_loggedin() ){
			$this->attire->set_layout('index/main',$data);
			$this->attire->add_view('menu');
			$this->attire->render();
		} 
		else {
			
			$data['css'] = "page-md login";
			
			$this->attire->set_layout('login/login',$data);
			$this->attire->render();
		}  
	}

}
```
cuando quiero renderizar el $this->attire->set_layout('index/main',$data); no me esta mostrando la vista menu. Ya probé guardar el archivo con extensión .twig y .php
Probé guardando el archivo de las siguiente maneras
1- /themes/admin/
2- /themes/adinn/layout/

Y en ninguna de las dos ocasiones me mostro el contenido del archivo menu.

Por otro lado la funcion include nativa de twig no esta soportada por attire porque la quise usar y me tiro error.

Desde ya muchas gracias!

**Comment by davidsosavaldes** [comment]
Tranquilo lucas, no desesperes.

Primero que nada recuerda que los `layouts` se guardan en el directorio 'layouts' dentro de tu tema:

    /themes/admin/layouts/index/login.twig #esto debería de ser correcto

También te comento que la función nativa de twig `include` SI esta soportada por attire, será posible que muestres dicho error?
