### ISSUE TITLE
assets css url

### ISSUE THREAD

**Issue by davidsosavaldes** [davidsosavaldes/Attire#2]
there's one big problem with url() function inside css asset files.

https://github.com/vendethiel/Sprockets-PHP/issues/37

**Comment by davidsosavaldes** [comment]
`Asset exception (path/to/app/bower_components/bootstrap/dist/css/bootstrap.min.css) : The asset file 'bootstrap/dist/css/../fonts/glyphicons-halflings-regular.woff2' of type 'woff2' wasn't found.`

**Comment by davidsosavaldes** [comment]
fixed with [https://github.com/vendethiel/Sprockets-PHP/pull/40](https://github.com/vendethiel/Sprockets-PHP/pull/40)

**Comment by oniricosistemas** [comment]
estoy obteniendo el mismo error, ya tengo actualizado la libreria y el theme :

> Asset exception >(C:\xampp\htdocs\punk\application\themes/bootstrap/assets/stylesheets/bootstrap.css) : The asset file >'glyphicons-halflings-regular.eot' of type 'eot' wasn't found.

**Comment by davidsosavaldes** [comment]
Nunca se realizaron pruebas con el SO de Windows, durante el transcurso de esta mañana realizaremos las pruebas unitarias dentro de ese entorno. 

Muchas gracias por tu reporte Lucas.

**Comment by davidsosavaldes** [comment]
Lucas, verifica que el paquete de Sprockets-PHP la tengas instalada con la versión "dev-master"
