### ISSUE TITLE
errores version 3.0 y sugerencias

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#29]
Hola, 
he actualizado a la versión nueva y me han empezado surgir errores por todos lados jejeej que no me dejan ingresar a mi sitio de pruebas.
Tengo este error:

> Exception: Attire_theme with the message: The directory "C:\xampp\htdocs\punk\application\libraries/Attire/dist/admin" does not exist.

la estructura de mi carpetas es:

- applications
- - themes
- - -  admin
- - - - - assets
- - - - -  layouts
- - - - - - - index
- - - - - - - login

que tengo que haer crear la carpeta admin dentro de application\libraries/Attire/dist

sugerencia: se podria aplicar alguna forma para poder setear mas de un theme, por ejemplo en mis sistemas tengo un administrador y un frontend, estaría bueno poder setear un theme para el administrador y otro para el front desde el archivo de configuracion.

saludos

**Comment by davidsosavaldes** [comment]
Un gran gusto en saludarte Lucas, la razón principal por la cuál dividimos la nueva versión a la antigua (como podrás ver en el repositorio) es porque son 2 arquitecturas totalmente diferentes, sin embargo, puedes regresar a la versión 2.x más estable con el siguiente comando usando composer:

    composer require "dsv/attire:~2.0"

En respuesta a tu sugerencia, se puede cambiar dinámicamente el tema desde algún método o controlador usando `Attire_theme` de la siguiente manera:

    $this->attire->theme->setName('bootstrap')->setLayout('jumbotron');

De esta manera puedes agregar una condición que te permita decidir cual tema/layout se debe de mostrar antes de renderizar la vista. Más información la puedes encontrar en la documentación de [Temas](http://davidsosavaldes.github.io/Attire/docs/v3/#themes)

También me gustaría comentarte que estoy trabajando en una nueva actualización que permitirá extender el tema actual, espero poder realizar las pruebas correspondientes en el transcurso de la semana que viene y poder liberarla. 

Muchas gracias por tus sugerencias y comentarios

**Comment by davidsosavaldes** [comment]
Se me olvidava mencionar, una estructura aceptable que puedes usar de ejemplo para actualizar tu sistema es la del tema de bootstrap:

https://github.com/davidsosavaldes/Attire-Bootstrap/tree/a3.0-compat

Recuerda verificar los cambios principales en el archivo de configuraciones de attire (dist/config/attire.php) y cambiarlos a tus necesidades.
