### ISSUE TITLE
reemplazar errores CI

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#36]
Hola,
necesitaría saber si es posible cambiar el template de errores de CI que vienen por defecto por unos que se generen con el motor de Attire. Por ejemplo si tengo un theme para administración y otro para frontend me tome el master.twig que corresponda y añada los estilos necesarios.
Saludos

**Comment by davidsosavaldes** [comment]
Ya lo he revisado y si es posible.

El método [_showError](https://github.com/davidsosavaldes/Attire/blob/develop/Attire.php#L157) define la salida de mensajes, lo único que necesitas cambiar en tu aplicación son los mensajes de error por default de CodeIgniter.

https://codeigniter.com/user_guide/general/errors.html
