### ISSUE TITLE
 deprecated since version 1.21

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#37]
Hola,
estoy usando una librería que guarda en la base de datos los errores de php y me esta guardando los siguientes errores:

> Using an instance of "Twig_Function_Function" for function "ci_*" is deprecated since version 1.21. Use Twig_SimpleFunction instead

en la linea 1365 del archivo vendor\twig\twig\lib\Twig\Environment.php

> Passing a name as a first argument to the Twig_Environment::addFunction method is deprecated since version 1.21. Pass an instance of "Twig_SimpleFunction" instead when defining function "ci_*".

en la linea 110 del archivo vendor\twig\twig\lib\Twig\Environment.php

> The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.

en la linea 12 del archivo vendor\twig\twig\lib\Twig\Function.php

> The Twig_Function_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead.

en la linea 13 del archivo vendor\twig\twig\lib\Twig\Function\Function.php

> Using "true" as the default strategy is deprecated since version 1.21. Use "html" instead.

en la linea 56 del archivo vendor\twig\twig\lib\Twig\Extension\Escaper.php

Yo se que seteando para que no muestre ciertos errores lo solucione tal vez, pero estaría bueno que ya vengan solucionado desde la libreria de ser posible.

Saludos
Lucas

**Comment by davidsosavaldes** [comment]
Que versión estas usando Lucas?

**Comment by davidsosavaldes** [comment]
Ya he hecho un pequeño cambio en la v2.0.x, puedes actualizar para ver si persisten los warnings?
