### ISSUE TITLE
error $config['functions']

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#5]
Hola,
intente configurar funciones en el archivo attire.php pero me esta dando error. En el archivo /libreries/attire/dist/config/attier.php tengo esto:
```php
$config['functions'] = array(
	'base_url' => function($path){ 
		return base_url($path); 
	},);
```

en master.twig tengo lo siguiente:
```twig
{% block stylesheets %}
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=all" rel="stylesheet" type="text/css" />

		{{base_url('admin/css/*')}}
	{% endblock %}
```

y cuando quiero renderizar el theme me sale este error:

> Attire::render()
> 
> Unknown "base_url" function in "master.twig" at line 16.

Saludos

**Comment by davidsosavaldes** [comment]
Para que las configuraciones de la librería funcionen, debes de pasar el archivo `/libreries/attire/dist/config/attire.php` a tu directorio de configuraciones de Codeigniter: `application/config/attire.php`. 

Como detalle adicional, he agregado un nuevo método que te permite implementar cualquier función sin necesidad de declarara en el archivo de configuraciones, como anteriormente se hacia.

**Ejemplo de uso:**

En tu archivo de vista, agrega el prefijo `ci_` a cualquier función que quieras llamar:

    {{ ci_base_url(''admin/css/*") }}

Para que **Attire** pueda encontrar esa función deberás de cargar el helper/libreria/etc en el controlador antes de renderizar el tema:

    <?php
    defined('BASEPATH') OR exit('No direct script access allowed');    

    class Foo extends CI_Controller {    

    	public function index()
    	{
    		$this->load->library('attire/attire');    

    		$this->load->helper('url');    

    		$this->attire->add_view('bar')->render();
    	}    

    }    

Cualquiera de los dos tipos de llamada funcionan actualmente, por lo cuál no te tienes que preocupar por seguir el nuevo método.
