### ISSUE TITLE
[New Theme] Yahoo Pure

### ISSUE THREAD

**Issue by absalomedia** [davidsosavaldes/Attire#6]
I've created a baseline Yahoo PureCSS theme, which does include all the base layouts CSS as well as Font Awesone,

It's available here [https://github.com/absalomedia/attire-theme-pure](https://github.com/absalomedia/attire-theme-pure)

**Comment by davidsosavaldes** [comment]
This is awesome!!

Thanks for your contribution. I will add your theme to the `docs`, so everyone can download it.

**Comment by davidsosavaldes** [comment]
done!!

http://davidsosavaldes.github.io/Attire/ack/
