### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by absalomedia** [davidsosavaldes/Attire#7]
I'm in the middle of trying to refactor a vanilla CI build into Attire & the documentation is a little light on what happens once you've created the template. I'm trying to find functional equivalents to something like this:
`$this->load->view('install/install_index', $data)`
which is passing a lot of data into & outside of the view.

Attire, as it stands, just generates the views. How do I pass data into it & out of it?

**Comment by davidsosavaldes** [comment]
Thanks for your feedback. 

I talk about that topic in this section http://davidsosavaldes.github.io/Attire/docs/#adding-views. There are 2 different ways to pass data to the views:

    $this->attire->add_view('install/install_index', $data);

Witch is equivalent to `$this->load->view('install/install_index', $data)`. 

Also if you want to pass the same data to all views rendered you can do it as follows (chain method):

    $this->attire->add_global('<name>', '<value>')
                       ->add_view('install/install_index')
                       ->add_view('install/another_index');

I'm going to rewrite some sections of the docs considering the lack of information.
