### ISSUE TITLE
CACHE_DIRECTORY path

### ISSUE THREAD

**Issue by oniricosistemas** [davidsosavaldes/Attire#8]
Hola, 
me actualice la versión de Attire y me empezó a tirar este error:

> Attire::render()

>CACHE_DIRECTORY:[C:\xampp\htdocs\punk/public/assets/] is not writeable.

revisando encontré que en el archivo libreries/Attire/Attire.php en la linea 211 esta:
```php
empty($this->assets_path) && $this->assets_path = FCPATH.'public/assets/';
```
Y si lo cambio a : 
```php
empty($this->assets_path) && $this->assets_path = FCPATH.'assets/';
```

y si uso el archivo de configuración también hay que cambiar de:
```php
$config['assets_path'] = FCPATH.'public/assets/';
```
a:
```php
$config['assets_path'] = FCPATH.'assets/';
```
ya no me arroja ese error.

Saludos

**Comment by davidsosavaldes** [comment]
Bueno, esto se debe a que se recomienda que pongas todos los archivos de css, js, etc lo mas lejos posible de tu directorio principal de la aplicación.

Tu configuración es correcta, únicamente era necesario darle permisos de lectura y escritura al directorio `public` por default.

https://github.com/joostvanveen/codeigniter-best-practises
